---
title: "Visualizing Toronto Miscellanueous Calls Data in 5 Years"
Purpose: Get data on 2021 homeless shelter usage and make table
Author: Rae Zhang
Email: junwei.zhang@mail.utoronto.ca
Date: 29 January 2023
Prerequisites: n/a
format: pdf
Abstract: "Toronto is Canada's largest city and is North America's fifth most populous municipality – with a population of 2.9 million people. In such a large city, it is very important to keep the track of 911 calling data to make sure the toronto police station have enough operators to solve emergencies. Upon further examination of data collected from the Open Data Portal of the City of Toronto, it was easy to find interesting trends in 911 calling services from year 2014 to 2021. I found trends in __________ . This paper attempts to visualize the trends as well as touch some problems that might to extract real meaning from the data."
---

## 1 Introduction

As one of the largest municipal police services in North America, Toronto Police Service and its Communications Centre serve the city with the largest population in Canada. The call centre answers all emergency 9-1-1 calls for police, fire and ambulance across the city. Operators are responsible for transferring to the appropriate emergency response team, dispatching police services when required, and assigning a priority level to the call.

The data about Toronto Emergency Call Centre is indispensable in helping improve the responding speed. Understanding who is calling, the types of phone calls that were receiving, the changes that occurs in different years, can help the Toronto Police Service better respond emergencies that happens in the city, and ensure a relatively safe and trusting environment for every member who lives and works at Toronto. The access of open source dataset also helps transparency, promote trust and gain meaningful insights from the data, while doing so in a secure and compliant environment.

The remainder of this paper is structured as follows: Section 2 covers the data source and analysis methodology employed. Section 3 then examines key dimensions of the data, proposing conclusions and areas of further exploration.

## 2 Data

### 2.1 Data Source

This report examines Toronto's Miscellaneous Calls for Service from 2014 to 2021. This data is provided by the Toronto Police Service. Toronto Police Service is committed to the ongoing release of open data for public safety, awareness, greater openness and transparency. This specific dataset includes the following categories of data including languages, calls received, and alarm calls for 2014 -- 2021. The R package opendatatoronto (Gelfand 2020) was used to obtain all relevant data.

### 2.2 Data Collection

The source of the information provided in the ASR is derived from Versadex, the Toronto Police Service records management system. Currently in Versadex, records are available for extraction January 1, 2014 onwards. The calling data comes from a combination of an automated and manual systems maintained by the operator units responsible.

The system recorded the call counts that are catagorized by different type of the reports, is it a valid or false alarm, as well as the type of the call, is it an emergency, non-emergency, or a multi-language report, including: Arabic, Chinese, Croatian, Farsi, French, German, Greek, Hindi, Hungarian, etc.

### 2.2 Data Analysis
